### PR TITLE
Chapter on Async

### PR DESCRIPTION
**Pull request by mbifulco**
This is a direct copy from the Google Doc we were working on - lots left to do here.  I'll add comments from the doc in the PR here

### CODE REVIEW

**Comment by philsturgeon** [comment]
The error handling I thought we'd be talking about here, is that if there is some work which often fails its nice to wrap it in a worker (service worker in the browser, or something like [Faktory](https://www.mikeperham.com/2019/01/16/using-faktory-with-javascript/) for backend things).

Then if something is failing it just "thrashes" a bit in the worker, fails, retries later, and hopefully eventually does the thing. In the mean time it can update the UI with progress, through toast (gross), progress bars, etc. This is better than having the user resubmit the data, and they can go around doing other stuff, unblocked by this shitty upload. This is not how you want things to work for card payments but maybe for file uploads. 

Then there's the akwardness of: a web hook coming from some provide just let us know the payment failed for this card payment, and they are still on the page, I guess we comminicate the fail and update that screen. What if we chose to let them continue browsing around the site, or have no idea if they are still there or not. Send an email I guess?

Anyhow, I think there is good content here but it needs focus: what is the point of this chapter.

1. Not building UIs that wait for the API to say "Yep, I'm done!" before moving on
2. the technologies and practices which can help you do that
3. how to handle errors from those async messages 
4. how to keep an eye out for common versioning practices in the messages/events (remembering that we just talked about change management in general in a previous chapter)

**Review by philsturgeon — COMMENTED** [review]
I had some old comments knocking around on this PR. Can you accept em and I'll merge this thing.

**Review by philsturgeon — APPROVED** [review]
Actually no lets merge this and I'll take a swing at those changes myself. Thank you!

**Comment by mbifulco** [comment]
🙌🏻

**Pull request merged**
